import { Component } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { NgZorroModule } from '../../shared/ng-zorro.module';

@Component({
  selector: 'app-employees',
  imports: [FormsModule, ReactiveFormsModule, NgZorroModule],
  templateUrl: './employees.html',
  styleUrl: './employees.scss',
})
export class EmployeesComponent {
  tooltipMouseEnterDelay = 1;
  toolTipPlacement = 'topLeft';

  selectedStatus = 'All';

  options = [
    { label: 'Active', value: 'Active', icon: 'check-circle' },
    { label: 'All', value: 'All', icon: 'play-circle' },
    { label: 'Inactive', value: 'Inactive', icon: 'close-circle' },
  ];

  tableData = [
    {
      name: 'Akhil Manikandan',
      email: 'akhil.manikandan@speehive.com',
      phone: '9876543210',
      address: '123 Main St, Anytown, USA',
      status: 'Active',
      designation: 'Senior Software Engineer',
      projectName: 'Trackline',
      experience: 6,
    },
    {
      name: 'Rahul Sharma',
      email: 'rahul.sharma@gmail.com',
      phone: '9876543211',
      address: '45 MG Road, Bengaluru, India',
      status: 'Active',
      designation: 'Frontend Developer',
      projectName: 'Client Portal',
      experience: 4,
    },
    {
      name: 'Priya Nair',
      email: 'priya.nair@yahoo.com',
      phone: '9876543212',
      address: '12 Marine Drive, Kochi, India',
      status: 'Active',
      designation: 'UI/UX Designer',
      projectName: 'Design System',
      experience: 5,
    },
    {
      name: 'Arjun Patel',
      email: 'arjun.patel@outlook.com',
      phone: '9876543213',
      address: '78 SG Highway, Ahmedabad, India',
      status: 'Inactive',
      designation: 'Backend Developer',
      projectName: 'API Gateway',
      experience: 7,
    },
    {
      name: 'Sneha Reddy',
      email: 'sneha.reddy@gmail.com',
      phone: '9876543214',
      address: '9 Jubilee Hills, Hyderabad, India',
      status: 'Active',
      designation: 'QA Engineer',
      projectName: 'Automation Suite',
      experience: 3,
    },
    {
      name: 'Vikram Singh',
      email: 'vikram.singh@gmail.com',
      phone: '9876543215',
      address: '22 Connaught Place, Delhi, India',
      status: 'Active',
      designation: 'Project Manager',
      projectName: 'Enterprise Dashboard',
      experience: 10,
    },
    {
      name: 'Ananya Iyer',
      email: 'ananya.iyer@gmail.com',
      phone: '9876543216',
      address: '4 T Nagar, Chennai, India',
      status: 'Inactive',
      designation: 'Business Analyst',
      projectName: 'Requirements Hub',
      experience: 6,
    },
    {
      name: 'Rohit Mehta',
      email: 'rohit.mehta@gmail.com',
      phone: '9876543217',
      address: '18 Bandra West, Mumbai, India',
      status: 'Active',
      designation: 'DevOps Engineer',
      projectName: 'Cloud Migration',
      experience: 8,
    },
    {
      name: 'Pooja Verma',
      email: 'pooja.verma@gmail.com',
      phone: '9876543218',
      address: '56 Alambagh, Lucknow, India',
      status: 'Active',
      designation: 'HR Executive',
      projectName: 'Employee Hub',
      experience: 4,
    },
    {
      name: 'Karan Malhotra',
      email: 'karan.malhotra@gmail.com',
      phone: '9876543219',
      address: '101 Sector 18, Noida, India',
      status: 'Active',
      designation: 'Full Stack Developer',
      projectName: 'Billing System',
      experience: 6,
    },
    {
      name: 'Neha Gupta',
      email: 'neha.gupta@gmail.com',
      phone: '9876543220',
      address: '34 Civil Lines, Jaipur, India',
      status: 'Inactive',
      designation: 'Support Engineer',
      projectName: 'Helpdesk',
      experience: 5,
    },
    {
      name: 'Amit Kulkarni',
      email: 'amit.kulkarni@gmail.com',
      phone: '9876543221',
      address: '77 Deccan Gymkhana, Pune, India',
      status: 'Active',
      designation: 'Tech Lead',
      projectName: 'Core Platform',
      experience: 11,
    },
    {
      name: 'Ritika Bose',
      email: 'ritika.bose@gmail.com',
      phone: '9876543222',
      address: '11 Salt Lake, Kolkata, India',
      status: 'Active',
      designation: 'Data Analyst',
      projectName: 'Analytics Engine',
      experience: 4,
    },
    {
      name: 'Suresh Kumar',
      email: 'suresh.kumar@gmail.com',
      phone: '9876543223',
      address: '90 RS Puram, Coimbatore, India',
      status: 'Inactive',
      designation: 'System Administrator',
      projectName: 'Infrastructure',
      experience: 12,
    },
    {
      name: 'Meera Joshi',
      email: 'meera.joshi@gmail.com',
      phone: '9876543224',
      address: '14 Alkapuri, Vadodara, India',
      status: 'Active',
      designation: 'Product Owner',
      projectName: 'Roadmap Planning',
      experience: 9,
    },
    {
      name: 'Nitin Chawla',
      email: 'nitin.chawla@gmail.com',
      phone: '9876543225',
      address: '3 Model Town, Ludhiana, India',
      status: 'Active',
      designation: 'Security Engineer',
      projectName: 'IAM Platform',
      experience: 7,
    },
    {
      name: 'Shalini Kapoor',
      email: 'shalini.kapoor@gmail.com',
      phone: '9876543226',
      address: '8 Rajouri Garden, Delhi, India',
      status: 'Inactive',
      designation: 'Content Manager',
      projectName: 'Knowledge Base',
      experience: 6,
    },
    {
      name: 'Manoj Yadav',
      email: 'manoj.yadav@gmail.com',
      phone: '9876543227',
      address: '66 Gomti Nagar, Lucknow, India',
      status: 'Active',
      designation: 'Mobile App Developer',
      projectName: 'Android App',
      experience: 5,
    },
    {
      name: 'Divya Mishra',
      email: 'divya.mishra@gmail.com',
      phone: '9876543228',
      address: '29 MP Nagar, Bhopal, India',
      status: 'Active',
      designation: 'Scrum Master',
      projectName: 'Agile Transformation',
      experience: 8,
    },
    {
      name: 'Sanjay Rao',
      email: 'sanjay.rao@gmail.com',
      phone: '9876543229',
      address: '5 Indiranagar, Bengaluru, India',
      status: 'Inactive',
      designation: 'Database Administrator',
      projectName: 'DB Optimization',
      experience: 13,
    },
    {
      name: 'Kavya Menon',
      email: 'kavya.menon@gmail.com',
      phone: '9876543230',
      address: '19 Vyttila, Kochi, India',
      status: 'Active',
      designation: 'Marketing Analyst',
      projectName: 'Growth Metrics',
      experience: 3,
    },
    {
      name: 'Deepak Soni',
      email: 'deepak.soni@gmail.com',
      phone: '9876543231',
      address: '41 New Market, Indore, India',
      status: 'Active',
      designation: 'Finance Analyst',
      projectName: 'Cost Optimization',
      experience: 6,
    },
    {
      name: 'Ramesh Pillai',
      email: 'ramesh.pillai@gmail.com',
      phone: '9876543232',
      address: '27 Kowdiar, Trivandrum, India',
      status: 'Inactive',
      designation: 'Operations Manager',
      projectName: 'Process Improvement',
      experience: 14,
    },
    {
      name: 'Swathi Rao',
      email: 'swathi.rao@gmail.com',
      phone: '9876543233',
      address: '10 Gokulam, Mysuru, India',
      status: 'Active',
      designation: 'QA Lead',
      projectName: 'Test Strategy',
      experience: 9,
    },
    {
      name: 'Harish Anand',
      email: 'harish.anand@gmail.com',
      phone: '9876543234',
      address: '88 Fraser Road, Patna, India',
      status: 'Active',
      designation: 'Solution Architect',
      projectName: 'Enterprise Architecture',
      experience: 15,
    },
  ];
}
